version: "3.9"
services:
  recorder:
    platform: linux/arm64
    build: .
    volumes:
      - ./output:/output
    environment:
      WEB_APP_URL: "https://google.com"
      FPS: "12"
      GIF_NAME: "walkthrough.gif"
